### ISSUE TITLE
Run error

### ISSUE THREAD

**Issue by yuanyuan12543** [OrensteinLab/SWOffinder#2]
Hi, I am trying to run the code below,
java -cp bin SmithWatermanOffTarget.SmithWatermanOffTargetSearchAlign /blue/vulpe/zjl1983/var/chromosome/canFam6/canFam6.fa sgRNA_titin.txt SWOF 4 5 5 2 1 false NGG false

However, I got the error message as below,
Exception in thread "main" java.lang.NumberFormatException: For input string: "NGG"
        at java.base/java.lang.NumberFormatException.forInputString(NumberFormatException.java:67)
        at java.base/java.lang.Integer.parseInt(Integer.java:665)
        at java.base/java.lang.Integer.parseInt(Integer.java:781)
        at SmithWatermanOffTarget.SmithWatermanOffTargetSearchAlign.main(SmithWatermanOffTargetSearchAlign.java:630)

This is my sgRNA.txt file
ATTGCCGCAGGTTCTGGAACNGG
CCTCAGTACAAGTTTCAGGTNGG
AGTACAAGTTTCAGGTTGGTNGG
CAAGTTTCAGGTTGGTTGGTNGG

I could not figure out the reason for the error, could you please help me out?

Thank you!

**Comment by ofiryaish** [comment]
Hi,

I think this is because you did not insert the `Best in-a-window size` argument. The README was wrong by saying to insert only if Best in-a-window is true. I fixed it now. 

Please confirm or tell me if this is not the problem.

Thank you for pointing this out!

**Comment by ofiryaish** [comment]
@yuanyuan12543 Can you please confirm the issue is solved?

**Comment by yuanyuan12543** [comment]
Sorry for forgetting to do so. Yes. The issue is solved.

Thank you ！
