### ISSUE TITLE
run error at split fasta

### ISSUE THREAD

**Issue by mzhibo** [OrensteinLab/SWOffinder#5]
Thanks for developing and sharing this package.
I am giving it a try but encountered a error: 

```
java -cp $binPath SmithWatermanOffTarget.SmithWatermanOffTargetSearchAlign $genomePath $sgRNA_list_file $OutputPrefix 7 6 6 1 6 true 2 NGG false
Saved sequence �;�-���?_�i���g;xۗ����.��8S��w���a���+�x[�c to file /mnt/efs/home/zma/resources/genomes/GRCh38/UCSC/hg38.p14.UCSC_latest_v20221027.fa_split/�;�-���?_�i���g;xۗ����.��8S��w���a���+�x[�c.txt
Saved sequence ��_\��y��i�� to file /mnt/efs/home/zma/resources/genomes/GRCh38/UCSC/hg38.p14.UCSC_latest_v20221027.fa_split/��_\��y��i��.txt
java.io.FileNotFoundException: Invalid file path
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:229)
        at java.base/java.io.FileOutputStream.<init>(FileOutputStream.java:123)
        at java.base/java.io.FileWriter.<init>(FileWriter.java:66)
        at SmithWatermanOffTarget.FastaReader.saveSequenceToFile(FastaReader.java:72)
        at SmithWatermanOffTarget.FastaReader.splitFastaToFiles(FastaReader.java:28)
        at SmithWatermanOffTarget.SmithWatermanOffTargetSearchAlign.main(SmithWatermanOffTargetSearchAlign.java:664)
total Execution time: 173 milliseconds
```

Any suggestion on how to fix this?
```
java --version
openjdk 17.0.12 2024-07-16 LTS
OpenJDK Runtime Environment Corretto-17.0.12.7.1 (build 17.0.12+7-LTS)
OpenJDK 64-Bit Server VM Corretto-17.0.12.7.1 (build 17.0.12+7-LTS, mixed mode, sharing)
```

**Comment by ofiryaish** [comment]
Dear @mzhibo

Thank you for your interest in the tool.

Can you share with me the full command you tried to run? I see it with `$` symbols, I think the program was unable to find the path or something like that, as it states:
`java.io.FileNotFoundException: Invalid file path`

Looking forward to your response.

**Comment by mzhibo** [comment]
i figured it out. it was because I used hg38.fa.gz rather than hg38.fa
problem solved. running now

**Comment by ofiryaish** [comment]
@mzhibo thank you for your update.

Please let us know if you encounter other problems.
